version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx/
            - ./code:/var/www/project
        links:
            - php

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=toor987564321
            - MYSQL_DATABASE=project
            - MYSQL_USER=project
            - MYSQL_PASSWORD=project123465789

        volumes:
            - ./docker/mysql:/var/lib/mysql

    php:
        build: ./docker/php
        container_name: php-fpm
        volumes:
            - ./code:/var/www/project
        links:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8090:80

        links:
            - mysql:db